apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-example-com
  namespace: traefik
spec:
  secretName: wildcard-example-com-tls
  dnsNames:
    - "jacob-williams.me"
    - "*.jacob-williams.me"
  issuerRef:
    name: cloudflare
    kind: Issuer