---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-jacob-williams-me
  namespace: traefik
spec:
  secretName: wildcard-jacob-williams-me-tls
  dnsNames:
    - "jacob-williams.me"
    - "*.jacob-williams.me"
  issuerRef:
    name: cloudflare
    kind: Issuer