---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: traefik
spec:
  encryptedData:
    api-token: AgAJuAJ8+i6URBSUQYoX2M6ww+W4NzEcWmpxfHk1Y9oFlQu5Gad7aWAHpzNJJzCb5Evu4Ng96QDQsryzxDSlQQjlhJ5m0oERg2vhW3M1+Q3IYdJ9PaBVjouBC270FFu5yPuPzJCW8X+t9IEDLiIlnufkiX2nmLdKCidHLJw2xMuWYr8HSWaVDr1SM5KEgLggKa1KuQ9KwhwcPZxk8u/556xGwH+A22eLv6kZfm5MVBzRVUJBinmF6feAAaURXGtuFGSokdDA8ocZK7ET2E4MkUqtaHsGgAZB/7LAuGyjzKPHR5f/n+CafD+HH7ZuM8+ZDjAnmIVRegrWBjpAbQSI5ixpAmblbgqmQHldezEd7LH5utpBxv5wrTjTf4UnvMIOxYFIipLoDOlfm9fkDbuFF0hVQ8z3jDlOJwnA4NocZ5DwowpDColLAZ+uwqjGk2t77uG3Pc57xbd1sYfV8VDpSvlDq8/8ike1JALQrcQZRsU6jKBc/g8CU84rK5niOhOoLY/dhbaVSCGffHdQXtIpSs0Q1vjkuvZldHUJ3mqbB4+S3aaNO1wvxxqHGJWnMcrF+zEMyf3bbjlIEB1DDPDM7zECMiRssfBgQiiEehMK8jQUQ2TxOyT1kuhVM0T/o3a5o/9TwOBHFowXgnyw0/c/ljOcRfR94vzWEjOGZSWkTPqO7nR0tNJc+g44eSn+Oxiw/UysgNhkCBwOCGqn/FKAJx6O/CT2fH1LdP8zEBEnS0sTnys8u5TlnXyY1j/Zj/lMARR5CLxqAV1VgA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: traefik
    type: Opaque
