---
os: "linux"
arch: "amd64"

vip: 10.0.40.130

metallb_version: v0.13.12
lb_range: 10.0.40.150-10.0.40.170
lb_pool_name: first-pool

ansible_user: ubuntu
ansible_become: true
ansible_become_method: sudo

################################################################################
# options to change default values
# kube_vip_version: "v0.8.0"
# vip_interface: "eth0"
# rke2_version: "v1.29.4+rke2r1"
# rke2_install_dir: "/usr/local/bin"