---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: glauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: glauth-secret
    template:
      engineVersion: v2
      # Create passbcrypt:
      #   "https://gchq.github.io/CyberChef/#recipe=Bcrypt(12)To_Hex('None',0)"
      # or
      #   htpasswd -bnBC 10 "" YOUR_PASSWORD | tr -d ':\n' | od -A n -t x1 | sed 's/ *//g' | tr -d '\n'
      data:
        server.toml: |
          debug = true
          [api]
            enabled = true
            tls = false
            listen = "0.0.0.0:5555"
          [ldap]
            enabled = true
            listen = "0.0.0.0:389"
          [ldaps]
            enabled = false
          [backend]
            datastore = "config"
            baseDN = "dc=home,dc=arpa"
        groups.toml: |
          [[groups]]
            name = "svcaccts"
            gidnumber = 6500
          [[groups]]
            name = "admins"
            gidnumber = 6501
          [[groups]]
            name = "people"
            gidnumber = 6502
        users.toml: |
          [[users]]
            name = "search"
            uidnumber = 5000
            primarygroup = 6500
            passbcrypt = "{{ .GLAUTH_SEARCH_PASSWORD_BCRYPT }}"
            [[users.capabilities]]
              action = "search"
              object = "*"
          [[users]]
            name = "jacob"
            mail = "{{ .GLAUTH_JACOB_EMAIL }}"
            givenname = "Jacob"
            sn = "Williams"
            uidnumber = 5001
            primarygroup = 6502
            othergroups = [ 6501 ]
            passbcrypt = "{{ .GLAUTH_JACOB_PASSWORD_BCRYPT }}"
          [[users]]
            name = "elizabeth"
            mail = "{{ .GLAUTH_ELIZABETH_EMAIL }}"
            givenname = "Elizabeth"
            sn = "Williams"
            uidnumber = 5002
            primarygroup = 6502
            passbcrypt = "{{ .GLAUTH_ELIZABETH_PASSWORD_BCRYPT }}"
  dataFrom:
    - extract:
        key: glauth