---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Directories
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  TERRAFORM_DIR: "{{.ROOT_DIR}}/terraform"
  # Files
  AGE_FILE: "{{.ROOT_DIR}}/age.key"
  KUBECONFIG_FILE: "{{.ROOT_DIR}}/kubeconfig"
  PIP_REQUIREMENTS_FILE: "{{.ROOT_DIR}}/requirements.txt"
  # Binaries
  PYTHON_BIN: python3

env:
  VIRTUAL_ENV: "{{.ROOT_DIR}}/.venv"

includes:
  ansible: .taskfiles/Ansible/Taskfile.yaml
  kubernetes:
    aliases: ["k8s"]
    taskfile: .taskfiles/Kubernetes/Taskfile.yaml
  flux: .taskfiles/Flux/Taskfile.yaml
  sops: .taskfiles/Sops/Taskfile.yaml
  workstation: .taskfiles/Workstation/Taskfile.yaml
  cluster: .taskfiles/Cluster/Taskfile.yaml
  terraform: .taskfiles/Terraform/Taskfile.yaml

tasks:
  build-stack:
    cmds:
      - task: "terraform:build"
      - task: "cluster:install"
      - task: "flux:bootstrap"

  destroy-stack:
    cmds:
      - task: "ansible:run"
        vars:
          playbook: cluster-nuke
      - task: "terraform:destroy"