---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBcSWQTkhNLVmpVR5iQ9g7NRJY9mTJ5dfllqli9b4+Xs1pPoCGwlIKDXUn7esixv+jMBwmdg61Ls/PJpmqvGMe9H4O/pM0OXZyATYZA9ur7O0EatNVwpo+Fkp1SYrTbYQqdmeEc7YLuhphu/28B8NN98AKdb857vIIY88oLQDP83ZGtmd3kDAGPiuX49Yagk78UODevrH7t4R68sC6tzanj4/OvDVpx08C4Pi/lX2ZaEHZi6Kw9HkLQoSZG7lvLRWlgEFSeslSEreRNQOv4ErTMLoGncINcjxt7l98sXMSv8Bi2hFwLx3A+AZrBofXtqeIm7hvqknTkg/+AqpDFqcmX8+I4+1QLJVdEH/RdL+TU4plEivfwwgzw9fCo8bh+S+4KrzvuTFSmK+B3mwf6o2W3Ud7QAnjXUZ2RSyorYZzACctnXQwz5ICPZVOyBQf2mR8YGq24SAQ5rZGaMLz1XC/Y0NmKoLrja63e13uWDsO0714sc7mlNBp1O1x3i4Bljlr3LPvY54KW6rdnYomhaajjVIe7TgOl8vs2dhaAfZCaxSMJ952otahM5RPqxgC+1+JX7TpYQ9DWDijQGYHESL9+Lmlh+W1rI/pnNF6qDQQ7EG5Du4VkZgoHLfOifxKKkUtXhWXh3bxuT67izGXkDxFc3Ft/9YmO/zc0Rmeta08IH5ZTCErYYXqapWshVRr+UsXNNH3x3jl/TLX8jCkB4DmukL5MIfuvTAnr4cHNwU1ThsscUa/ejxwu
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: cert-manager
    type: Opaque
