---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBMl0+Rk0JAtwsPqgCAAuqAcbEdAH6Xk+Fgfm8hosplltwJBWtmba9mK/lGAXkJo3d20ji/OBlWv7n6NarIewRE7cZSkIsNfZCT9DQQI9Diru/9ii2onDw9c7QcziKxCr9n+Ev7BQmwiX26xy24kE6G1qYp7Bic6/9bDJHUxOQfkFmsG3CZj0px82OPp3NBE0RjZUFsXfRcCaRTXB2nrbP/XYGMLHC8EFY7KTtBQ66Szl1Mri+Eb0QWJ2nX9eZWCCeK/iPJmp1eKfWIhjfEbGyopEJl5is/QRnMLan+cPXjKEY2ON/2l3vtm/8dPtaqJFgZrdH6higLmxBT1fFNNmHTkYbvOVCpiCqndXPpf9Q7voIMcfbgUv3R6RGhU2s4y2YOdPpABDrnAs+JFZKsmH4db5vHJk6YZhIveDP7eF4VvtkjCZshUQUnDWmIO8oo9wSnyGcwtT9Ro4I8EZq4/z8T8FTlAqyPFWbpNUxIkrhnJnxU6bw3CgWs5LnoYNpC1dTysFjQ+DBkQYmPy244z7KbNWzXKVjUY/l/czPhcCtlsPlzUpU/tVhgmrkSgUGy/cCi2rnx8F53XM6wtk8OIK9JQ7W2dtveS1u0mZw3OvuSE9qLAWguQQ7i62IOcqBmciBSJMLERxPgypni+tYL48fLnXAb0kHSldHw+t1MsMeqwDvAVNyuqiqZPzCpuwArhpNtoAiF+Qxofacx9h8m/8hQs8I825a8eaCjR8tnYa/WPtFJBlqY/ffH
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: cert-manager
    type: Opaque
