apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - issuer.yaml
  - cloudflare-secret-sealed.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
spec:
  dependsOn:
    - name: operators
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/operators/configs