apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:YCAWHHqqAWuf2cmfeoEkI7rLP22d6ASONo8uiA5AzCOR04er,iv:39Y620iMSzdxuOWBSXFPreDBaIw1ctVJJkvLLpU7L04=,tag:cpJSZyILN+zdMq9v5H+07w==,type:str]
    credentials.json: ENC[AES256_GCM,data:6zjAWp3IHMVtdVYkKt9p3JZ/oGzmq9d6SjpDfqDFfppwbKcGlUsVZ0yvcx2HpdatMXCoDypGLRXyLCDMrG+Z6C6U0dYWhG8HPII0inJSlkNeDk1Cr/4d9DV0iKk85mBC6/Xr5e/GmDjXGX/6Y403XoBp5T8cLNlE65onVkJ51CbDXXGOTH3X3nF6FBIkno4=,iv:xt445ZMU1SxYWeR46sZNZ/MOB6uc/Qfys1O2x1d39Vg=,tag:7xHtWUaSNnuFgVpEz/PkzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zaf432f5rk6zdeteahr3m966qqd7tq8tfpk40x2slhrq74njy4jq6xcngl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaY0QxdU5XK2dyN2g4bXZI
            aGV5aSt6bWdNUnVyK2hQRkIrTWVMWU1kempJCml2M1Uvemd3cW5DSGVJcHBMcW5M
            dlBsc2oxd3Bkc1Q2WnBWUDhva0E5NE0KLS0tIDA2eHFwTEZxcHFMbmE0Vi9IYUtZ
            Qk5NeWRZV1RQZnJ0TWxXZGttbWQ5YWsKY/Un1A5g2hfIibLqMS3Cbl2qbuE7y07v
            muWsB3WTzyZE44lXKSScHeCcyXGXO7YhTiLt2fHuRQPFz5QLQAKupw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T00:12:17Z"
    mac: ENC[AES256_GCM,data:6J3dNyNLXU27Et4ykT17PXoHTClLKC4DGzv4mLuxWf34jWAtUo7RPlpxjm+NMQ3iunSTKadoRADAIsFxcSbIpYj/0hxbhhjiT6oeZo+8AanrwIDckIZvFF2QXmIJ5cLcopakBA7kniAnjKasGAM08cKQg9wVddlq5qW4B497yAY=,iv:l07SUM1n9DyOhHqzUS4pa5Or5DwkeWq2kRA6g6utqa8=,tag:aF3ySTi7G0sgotGsafv8xQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
