---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb-community-operator-crds
spec:
  interval: 30m
  chart:
    spec:
      chart: mongodb-community-operator-crds
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3