---
# Note: Authelia vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
authentication_backend:
  ldap:
    address: ldap://glauth.default.svc.cluster.local:389
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: dc=home,dc=arpa
    additional_users_dn: ou=people,ou=users
    users_filter: (&({username_attribute}={input})(objectClass=posixAccount))
    additional_groups_dn: ou=users
    groups_filter: (&(uniqueMember={dn})(objectClass=posixGroup))
    user: cn=search,ou=svcaccts,ou=users,dc=home,dc=arpa
    attributes:
      username: uid
      display_name: givenName
      group_name: ou
      mail: mail
      member_of: memberOf
  password_reset:
    disable: true
  refresh_interval: 1m

session:
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: jacob_williams_session
      domain: jacob-williams.me
      authelia_url: https://auth.jacob-williams.me
      default_redirection_url: https://jacob-williams.me
  redis:
    database_index: 2
    host: dragonfly.database.svc.cluster.local

notifier:
  disable_startup_check: true
  smtp:
    host: smtp-mail.outlook.com
    port: 587
    timeout: 5s
    username: jacob.t.williams@outlook.com
    password: "$${AUTHELIA_SMTP_APP_PASSWORD}"
    sender: "jacob.t.williams@outlook.com"
    identifier: "authelia"
    subject: "[Authelia] {title}"
    startup_check_address: "jacob.t.williams@outlook.com"
    disable_require_tls: false
    disable_html_emails: false
    tls:
      server_name: smtp-mail.outlook.com
      minimum_version: TLS1.2
      skip_verify: false

totp:
  disable: false
  issuer: authelia.com

webauthn:
  disable: true

duo_api:
  disable: true

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules: []

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - client_name: Grafana
        client_id: grafana
        client_secret: "$${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.jacob-williams.me/login/generic_oauth"]
        userinfo_signed_response_alg: none
      # - client_name: Miniflux
      #   client_id: miniflux
      #   client_secret: "$${MINIFLUX_OAUTH_CLIENT_SECRET}"
      #   public: false
      #   authorization_policy: two_factor
      #   pre_configured_consent_duration: 1y
      #   scopes: ["openid", "profile", "groups", "email"]
      #   redirect_uris: ["https://miniflux.devbu.io/oauth2/oidc/callback"]
      #   userinfo_signed_response_alg: none