apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
  namespace: kube-system
data:
  config.yaml: |
    peers:
      - peer-address: 10.0.40.1
        peer-asn: 65551
        my-asn: 65552
    address-pools:
      - name: default
        protocol: bgp
        addresses:
          - 10.0.40.150-10.0.40.200