---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: v1.6.1
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.jacob-williams.me"
      host: "longhorn.jacob-williams.me"
      ingressClassName: "internal"
    longhornManager:
      # nodeSelector:
      #   longhorn: "true"
      tolerations:
      - key: "longhorn-storage"
        operator: "Exists"
        effect: "NoSchedule"
    longhornDriver:
      nodeSelector:
        longhorn: "true"
      tolerations:
      - key: "longhorn-storage"
        operator: "Exists"
        effect: "NoSchedule"
    longhornUI:
      nodeSelector:
        longhorn: "true"
      tolerations:
      - key: "longhorn-storage"
        operator: "Exists"
        effect: "NoSchedule"