---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app glauth
spec:
  interval: 30m
  chart:
    spec:
      chart: runix/pgadmin4
      version: 1.25.3
      sourceRef:
        kind: HelmRepository
        name: pgadmin
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    ingress:
      enabled: true
      ingressClassName: "internal"
      hosts:
        host: pgadmin.jacob-williams.me