---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reloader
spec:
  chart:
    spec:
      chart: reloader
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
      version: 1.0.93
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: reloader
  targetNamespace: traefik
  upgrade:
    crds: CreateReplace