---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/schemas/service.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      unifi:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/unifi-network-application
              tag: 8.1.127-ls46
            env:
              MONGO_HOST: unifi-mongodb-svc.database.svc.cluster.local
              MONGO_PORT: 27017
              MONGO_DBNAME: unifi
              MONGO_USER:
                valueFrom:
                  secretKeyRef:
                    name: mongo-secret
                    key: username
              MONGO_PASS:
                valueFrom:
                  secretKeyRef:
                    name: mongo-secret
                    key: password
            ports:
              - name: stun
                containerPort: 3478
                protocol: UDP
              - name: syslog
                containerPort: 5514
                protocol: UDP
              - name: speedtest
                containerPort: 6789
                protocol: TCP
              - name: devicecom
                containerPort: 8080
                protocol: TCP
              - name: webadmin
                containerPort: 8443
                protocol: TCP
              - name: httpsredirect
                containerPort: 8843
                protocol: TCP
              - name: httpredirect
                containerPort: 8880
                protocol: TCP
              - name: apdiscovery
                containerPort: 10001
                protocol: UDP
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8080
                  initialDelaySeconds: 15
                  periodSeconds: 20
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8080
                  initialDelaySeconds: 5
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 1G1
              # limits:
              #   memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
    service:
      tcp:
        controller: unifi
        ports:
          speedtest:
            port: 6789
            targetPort: 6789
            protocol: TCP
          devicecom:
            port: 8080
            targetPort: 8080
            protocol: TCP
          webadmin:
            port: 8443
            targetPort: 8443
            protocol: TCP
          httpsredirect:
            port: 8843
            targetPort: 8843
            protocol: TCP
          httpredirect:
            port: 8880
            targetPort: 8880
            protocol: TCP
      udp:
        controller: unifi
        ports:
          apdiscovery:
            port: 10001
            targetPort: 10001
            protocol: UDP
          stun:
            port: 3478
            targetPort: 3478
            protocol: UDP
          appdiscovery:
            port: 1900
            targetPort: 1900
            protocol: UDP
          syslog:
            port: 5514
            targetPort: 5514
            protocol: UDP
    # serviceMonitor:
    #   app:
    #     serviceName: unifi
    #     endpoints:
    #       - port: http
    #         scheme: http
    #         path: /metrics
    #         interval: 1m
    #         scrapeTimeout: 10s
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.jacob-williams.me"
        hosts:
          - host: "{{ .Release.Name }}.jacob-williams.me"
            paths:
              - path: /
                service:
                  identifier: tcp
                  port: 8443
