---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mongodb-secret
    template:
      engineVersion: v2
  data:
    - secretKey: username
      remoteRef:
        key: mongodb
        property: MONGO_USER
    - secretKey: password
      remoteRef:
        key: mongodb
        property: MONGO_PASSWORD