---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb-community-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: community-operator
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  values:
    community-operator-crds:
      enabled: false