apiVersion: v1
kind: Service
metadata:
  name: frigate
spec:
  ports:
  - name: http
    port: 10500
    targetPort: 10500
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: frigate-endpoint
  labels:
    kubernetes.io/service-name: frigate
addressType: IPv4
ports:
  - name: ''
    appProtocol: http
    protocol: TCP
    port: 10500
endpoints:
  - addresses:
      - "10.0.0.14"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: "internal"
  rules:
  - host: frigate.jacob-williams.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frigate
            port:
              number: 10500
