apiVersion: v1
kind: Service
metadata:
  name: truenas
spec:
  ports:
  - name: http
    port: 444
    targetPort: 444
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: truenas-endpoint
  labels:
    kubernetes.io/service-name: truenas
addressType: IPv4
ports:
  - name: ''
    appProtocol: http
    protocol: TCP
    port: 444
endpoints:
  - addresses:
      - "10.0.0.14"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truenas
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: "internal"
  rules:
  - host: truenas.jacob-williams.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: truenas
            port:
              number: 444
