---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  - ./crds/backup.yaml
  - ./crds/cluster-image-catalog.yaml
  - ./crds/cluster.yaml
  - ./crds/image-catalog.yaml
  - ./crds/pooler.yaml
  - ./crds/schedule-backup.yaml
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - config-map.yaml
  - deployment.yaml
  - mutating-webhook-configuration.yaml
  - namespace.yaml
  - service-account.yaml
  - service.yaml
  - validating-webhook-configuration.yaml