---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  chart:
    spec:
      chart: cnpg/cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      version: 0.21.2
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: cnpg
  targetNamespace: cnpg-system
  upgrade:
    crds: CreateReplace