---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: op-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgAkqy3Zo8iBwpHQd+U9ztLhk1mcFk/HLLqhj5NPSpa++ZJz6mzTUS9eV+FXwPMnXz6DmjMdib5WjuhtVNHJuo3rGOIWQh3qz7+LTRrLDRtkcmkrrUGfGY0lhFtiGMUMqCoMrT9UgLpBkvUFBkq1TqVAJVpfj7aj5S9bXScK+r9o2a4OKjdZLaKzPfZ6TX8mz35knPEjDcMdnBuCA3CvkSNB1xQScCMkVvnJnEmOVF5xkOb7ZOIusuiE5gunOoBgjYvtOD0ZC4L/43vncMmhECt0UCVW7UxxcTK+HNe0ERaKrSKuz7AfOCqf6sTr1dumaZUSvDtRn6k7R90afKkl0Fu5aPtkSSaV3aRbsAoffrdnjrF6oOH+lwgXOO62V35VqqUj0DP7Y/ekKJg6D58OrDwJ5vadM2DhvAe3j9vl+1wG24i0h0EcEskO5iAVikZCbrLftmW1LiY5B2OSmuwAmHjBsx7w98J5t6iEF+IlZ7z9wMGtYnF7Cc5k1cYhswz3hNc7VCrdqXIjySGVilVsh8yMHyULdOx9lIi/IGCcvIJuB1Kduo+wqw4zmjNPPBGxe0+aPs7omWd8i69YtrtbxUAQSVIlUb/zW0p9hPyHTv8+zvpj3CLZkdgKwaoVRGkoMAjbES3I1QkdgCkXeQaMpHFQv+phbSumgBL2XoQn47WDJ9JEUCCMyCgV/khdU1OU5nlPPyUgXOflWrpQ7C7q9slcO5uZwp3M48Tub71TIJ/SerV1kiOScOldXRYvy/Pm6SylDzUYB7Pm0XCuzhPNnt1l5B3HlJUF74LDG7wZJo0mTQZ3Q8AQTa81ktJyUHTAvnOjQa8T8viH6wUgoLrKP5/2XGeQ1pa9A0UJfbasRqJ51TjXuThaeIbdfzI7kZhTEw64Wh22QS3edNRQPBJTfLcNKL5H9lXOoVOZP/IOpeD53M+flrCwNBRSx/cCkt7zK6+dja2BuyEaiaHKINGVj7z/dzo0xtpDFiBjVPcZ/6kDndeg5ewsZ4/r/t/0rWuip99ZofId2erjR9PkwAh9HiIFCI9I+KtnmvN+JnrlgYkVc+g2y8ib3RFASAdiFod/qOT0lEmUyuOhDKG9fbfVrqnZDaqn6zFIRPz/1KP2WIK2selU6rGHyG4WEisdAhOjr7P1B+Xs/w7EfU1P9H+s/Nhe/+pGO3iF3Xdi5/DIVFJ5YPq7xbNLysnnTkqG5tc7yVOk2V3q+599DtqlgUeCmCAyZdHaCEiTduLsYl6aitwZIO6hqot4mdgMrQgei2WRAf+CqD5/lUUj6EzSavnBhqcUNai/IQhGhBYf/So1vxWqS1Zls4VBn4mhjSWPx/68JYQcJQNoAmqoCintRmqT4+JnRgpOaL1lP3nP2iFCBDwGhbn4M4uwNx4Q3MdYnWgKcfJJadk9WhU0fmmNhxq0Dp8mxIvwQScRF8vmPu7ieQvT7QkzwES3cVU9ODIdfiRo27EvPRAN7Kh3iQN368Xq317R43Ws3Cexzk20j0CAYGbbHAIk/Q/iPN50+kVs75ysJOK4LPeFWT7i6G2dR9Ne1aSAE9Q=
  template:
    metadata:
      creationTimestamp: null
      name: op-token
      namespace: external-secrets
