---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: op-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgBt/m2ZIZNF6mad+jyT/T/RQu7/hSiNPerG8v+a3SpYeUDsgZuVhfboNbZ9nuUqaIZinVxeIIeIQXZ7W7ySQcKJGSdcM9nksvf4PJU32lOQlPEsCTPqKwiBIJaXS2PugvgLP28F5E5EwirIJPhXhiOYbQ2RIAlZpf0s7zKrW2crbrCDqb2HheR8VkljuTc7cmjBTId3BZ938fdE4dJ6nYBSA2oQOMr3wfL2jB3OQP0nxv01fwY9QJmMsAb8yGfReEekQyqLXZoKzqPcBN1EhjGfGVlICgG+jEcgQ8+S+g9xJO5jFB1C00Yf8PQliJkc1PEajvyP0xWdPSJJ0CXzm84//U3kr9czz2Rw/Zn3Q0ra1KNB3vCy4klBq+yZ2M7BcpEGTHo6ew/qzOlJd1yZO0zFZ+YECeK2sVhhauUrqyBdVpTHi4eSQIcqBOgRBre0ujG2G/3bzQZG7tRGbofzBNbtpZlyZkuZSSuYCrpsOaMd1BMka3EEiO4/BKPfUylS1azhLEyBt6/pcXSmXB91aY8upNkHvqphic31C4jaF7upYQkzP9oFAFru1EnsNRTBc8Or632zVDfgSFlv0Ad1KmgCtBWfs5HMbyBudMnRzyNfZeX5zCF6zMoFPBAx0VthMXsUXZbeDGrEN6rwqA2TfRYiEo6/NlFWpus0/99kGc/A5O0g3pBYpr7XuYHTXPPPhqE/KRLNyV/CEpbLAmABKXSM1H/xxOUeOd1Opm3slUjDYDQqsFX9WIFS2xsVoiNeomvZmDRHZPB1l9uzxCSBRM9IbNZxsr/EZSGBppVc4bFqH6BfiE15lLNdWlc+UJSx2EBDxUeu08GRyfwvs29Azn5fSHP+UCpZJbrTDBdfCd/caHyUIJHvIRtX+n/SWo+ibmY1JidDU4ZmQp4L5iinQgGiW55MZw8+Qu6BASn8VU/jxMI7Ic24fWVKaSLGsLeSQIzgV+4bnOnIilyAYr5gO3lIRt8sqWSnE9H6HQ2ouy4ZEv0x4hzJIMRryANOgsNO1RPCDdMn1f+YC/aD0XV3NXxL6YcO2jI8JcLv4MiuAwLlAOV4+W711YJGTKm8FrucXdvX+0BEk4A2e5yECuKJxQ8NgsKUO9wGf3rSmpNLBBMXQ1JEeGFL3Bxx4xVVIKn1tWRY/PpYB/Y/QNEbw/EhyVVUf2lkFkiL7yvOIk+FBD1iDl8B7tqPIE8A+vL6thGd0hEm+p0Y3R4gGUM+i3bvM84ziEyTGrh69LTU4jTbHQw2A0QiIO/f+PHTLd4CeGdMfVvx/LypKLRg5gewb7nZFOQsBTHwQsw2d+tMJGzrUJm+D0QB2Lf2Vq/DO3z3ZbQCeu0Y3buH//YFUuANY/wupldOHN51krO95XwhYL8rcCcGxqsIBP+Cyixu31yrqDnwzaAezaospi9o1v4hOQoP8Jt7vBJ4LP8ie7DdO70Q2xagE5HUTi9Isx0J93OwI+TlCLxjBQj02LiLej5QCGZ0Bwx3opkh4FtykHss9qnlNLpQ949PcrFkvrO9gT8K3hrcPv/HlSugAZwFHSW11rIgvxGx1UD1
  template:
    metadata:
      creationTimestamp: null
      name: op-token
      namespace: external-secrets
