---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: op-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgBLrSo9DNKNpsZl5Y869a+0Bqpdf9G/eFe2mOAPFTzk9cdZtcl/1LL8wimOyXm1kRe5IIk1S1NymgvwYQB2QnnLCvG7PxkHZIIHB2Vy1lV9B9MZLTp+n9ygIqQDfgA9bdJXbrn73Tay4uwDPF/QKa8b9yje8urCiu7qPTvtf0QxukUZ6l3I8K4uulLbV5xRONuCkY+TSm4jZosgGlMTZvNzXijSSrUGHlyUzXGeOvnUEfpOMcnO+hVTOvHlKxz7aBvfhVlVnxZ98l1yhuPs38RQJUqA/guxqbVgCdqkS9NfQSGGGuIj2EaRp3TQ7+27SlUFl6EDfzucfDsTreoVuES7iNnt9jgiAovovT12vl4Na2JIr03n6luCBmsEXYfvPsnpZ4RhBosuk3U88pqMVRpYFlqK3xysuRtjlh5ZFEkJ4VSrbLjuI/kMQNTnkFBUnPu/8kL4F3JWpIkshpFMKA4rvvFtBSrwrwG9mKnhVENlb7GRYP+agsvfSJp+yjxnGD4H1ryZgxkPKzoJ78bFhCudEkLLGUk8wzBRpTVgappc2T6Pj1vvJjw4pP9fhjX7qHoybMUPd3MMJCsyf/gXOmcFkf4imOMTX8smxxdEb8pRok3Q5u7C9D482mlit6E5XmBEOSx9KC4uj2l5LsatPOhO5JwK1sBPSk5h0Z6/4VEpNpwhTEkDY3Cj++XnFrQ89DwvKrjAmblcJ3jaDqfpGmDB9RXmcufGXlga8PxpXLkqZ1qt2D/pJEAMib3DD31f7yk/ufbdq6gpApYb3K/sZbQCJ3aJUG1IXD9Ir2fx5no+w/aVL6eQT1U6hF4c+04fchTAcj9fs8nc0XByyxiPn4k3WbDcmdIih1SKVMaNrgFQv3/4fRV85QZFMwo1xR3O3E0Bxz1/Sq3kSFh4JN7YF4DJnXM6IGuZYZOcvzRwxFsVHdZLOZzscsg6nIIFNywysdf8UK2XNHlJSpRce2ndIDyE92f3u+FAea5v8v82Iyhcl0uSjYlwGCC3DgANfmO7VGOHW+Q8DkaKGFR9sgLcHYqSjzme6a91BuvRRhsrDeseh+B0tJ1NdKhxRDbp1Sh5BBfoGfIvYzAWI561U0eWssEzR6AncXEJV8vzwGEcWjGcYeoziPT+pGXRd7eHSehIEwJpLZ4pC/y2vPGfo7dQAZbDdgWK6sl6C2aKEgT6D1ZGAJkBZ7YNUezLaBnILu6AXWMeek0Z0lgJla9MzVAVI3HZIZo2vchUoq7T0qb0t+McR4hoYIFctFqYUZxbzQxblrkqzP0cAV1+EIH6bS54Kdb2OqZ4pslI6bNpUy3xMl50pP2SaQjxA7JSvuIcbJxueQfzRzlyuRKA9DFzaVAuwL2MgRXXM261cnNwRad4fg9QPqDVrOD1+zQCc3n9L1Jo7RSFKGzpBEli3P19ky8GgQMS5/tkt6MPugM8TLQGAOFhBWQLpYsEQrWD0lF4IGE3/XNf95rBXdg902qdHxsbwzrvIY2GiUdjvq9ZDXecXirQ9uP/glzQxNcUwnRVAXz9pjYfKPrD9V5XyemUgdDcm9arLH/Z
  template:
    metadata:
      creationTimestamp: null
      name: op-token
      namespace: external-secrets
