---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: op-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgCMMNKAsUua+A5gvjlF50sVV+Ut9LuNbHtFTlOf0XtVcB/YSTuugLufyyfMi6iQgSeJX8foQrPxIy/I8gjO2NafQ1eioP5saL8kKT+mlVH/+GGUNTC6JhHbWC4ztwEBSv5NjnJz7DFDiHQgww3flwRS4KS8UxIr4534+pvFcvCDuG99SLDGGw+N7aWm4Q+nBqVMPiefWgBy8cQjGL2p6c+i+27tIRuXy8qxoxAdDKswP+OhbZw1UIPKp4FEkF+79b9zoXBsLJxojs3L+KgbIPg4z5eKMoouMBgKwGFasP7dvopCQl7QRQ4ycDbLn+mXjQCeOyeOFoq5hJcZWRCng7Mc0DiIZAjVY64A8/JM0nqhUF1i3XEY9EVOlMQqkdQI50dyDWsu6BSH0z2Skk6CLNCAsJWHNwIq+rW+03Ftd255TEihMTvWt7GOHaa/BhQ13dzmOQo1efwpXPvRh1yEFtAeQk538wq2x5qfoiM/MP0IixQhc7g0GCd0cbyt6Tw1N7+0sd3sSTVyuBbbUiqHk8JDVIRk5d776Qzrddx4/BzwE2b4SszyQKsISrEx0N8LnIdWve8iukCXh/D8JVdReNVXQaqh1/KrjQWQVW9CihhYTZXeu5MqnY1oe2Zj6C0roic+x7bZQl0SW1DhED981ol6hHAXyQMiDuex+YKU5okxhod588chxq7xSDjHAfL3IiwlXy0NkmOEXRBDp4UCBFo34l2njNWzfulh1YFYb5pqQi/er0ZFgfJevScuSgw4fsQhK2NcNEu3+7pEYi1xF7UBILRhYnm3b9P2oi7xK+AQs2hrLDcJCNinyf67X5Nmp79IOnYI4EugoSVM8LpH7Is79D1QsO9ZOIS60JvLh6nqjKkSW6F8ZPNQmFG5zFKP46uU87vtp2PquuASrzXhVkKB+lF71NaXBi7/JLzuZSAVwWrPkVxMbKZGZXhuUs5hg2PvmkaXjYiOpQlBzskdQIBupd+vDSCo1iBhC6jX0qo77QcboqTcXTWo1XRfAz6d7kz2sBxB8Pwp84iu/PnKy+4hIWFWJWWlibd3v4GZRMMhUS9DbQTuwHW6DH16JoN2QLgAPpjDmX9/+zT04qSUELEk3JPWQ4h60MKwajS4Dyj8TGv6jyAjqjsbH3bHU2qvQpuZfOx1w9/fVE8t5tHwt81jaN2Mr/t2CdbiLMrzxXzs6Ub80L6v0oTSFSbVnrVR5LEFV+XoCWqws7ekHSsi7rOTr+max/3zsmqSrCVzNlEKdJgEgY76HAHmwbz2c7/eq600gDWC95C+L5z6ZxXTHyDGABzCXGc/YQoVCqNwSUJ3Dd/eGTfqAZH9tPhpBNG3eWq8H2e1dXJryMtpfaLbXCbG8kaOX9NEU+BHLPXyMUdZhnE/v+M3XCuJL7bxG7U/xjh0EjdJHdWKdEHgoJl99w8TBrtcNnBfGuefFVZgi0f+nGjHMAQV2im9+SYq7bkl8OfXpXxZcWi/nRL9l+kRt4S+/LSEQ6ZdgM2M7/kn1x0m54lPvM/1srkcsruuqQWYTN91vjhcK+v/fgzE10aQiO6cN9Y=
  template:
    metadata:
      creationTimestamp: null
      name: op-token
      namespace: external-secrets
