---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: default
spec:
  externalName: proxmox.home.arpa
  type: ExternalName
  ports:
  - name: websecure
    port: 8006
    targetPort: 8006