---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minio-tenant
spec:
  interval: 30m
  chart:
    spec:
      chart: tenant
      version: 5.0.10
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    tenant:
      pools:
        - servers: 4
          volumesPerServer: 1
          size: 2Gi
          storageClassName: longhorn
      configSecret:
        existingSecret: true