apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:C11CzWc2G3MWKSixsSxyhohjscN0J3Wy4zFctxQttME=,iv:Kgl58vCS60OOiDBb/1gTHLCpP8HXwD7Mi4BgDo1DHsA=,tag:FXxHYhwFrLnnIJjnYScDpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zaf432f5rk6zdeteahr3m966qqd7tq8tfpk40x2slhrq74njy4jq6xcngl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YmhIS292b2xoV2RZSm9j
            TjNwVWlMbUgvSFZpSkRmTmZJT1FnRStwbHd3CmM5YTZwUHNSZlUzQUg5cmJaWVZX
            dm13aXg2RDJjeDJVTzE5V1FERWhKZUUKLS0tIFM0U3JQZUhmOHRyRE0wa1Jqalgw
            aXB3dlF2Sk5jYVVONE9GWDkyQ01aQ00KxpUbyKELShMRUYpujckyCN7Y8ShK8ooY
            fROe7+VQ8QNkmR1bGOI6nIUMzexhhdFidCLeIh9qdrKugBxn5EGKVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-16T00:12:17Z"
    mac: ENC[AES256_GCM,data:0gbhK8UbLmLBsnJ5RaiiABibDUUo8Zg+NaowC1roLL32X+pQ2JCT6kXz37qafE70dRC/Kc+xHqZar3yHDMAiormEgw1HRaCEwK70dks/zv+Xsb5Wm02AQEZWKrP9VRM9oZYXfnsdlTgO2nCefvNzL+8muHulz6jZz22iwPh1o0M=,iv:e8xE65N+oVQxMDzKS/DIndWC/bxvxtYfHPyopwuBOkE=,tag:gBamoT70lV43XtiR/vh/4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
