---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authelia-secret
    template:
      engineVersion: v2
      data:
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .GLAUTH_SEARCH_PASSWORD }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "{{ .AUTHELIA_JWKS_PRIVATE_KEY }}"
        AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: "{{ .AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET }}"
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
        AUTHELIA_STORAGE_POSTGRES_DATABASE: &dbName "{{ .dbname }}"
        AUTHELIA_STORAGE_POSTGRES_ADDRESS: &dbHost "{{ .host }}.database.svc.cluster.local"
        AUTHELIA_STORAGE_POSTGRES_USERNAME: &dbUser "{{ .user }}"
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: &dbPass "{{ .dbpassword }}"
        AUTHELIA_SMTP_APP_PASSWORD: "{{ .AUTHELIA_SMTP_APP_PASSWORD }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OAUTH_CLIENT_SECRET }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: authelia-pg
    - extract:
        key: cloudnative-pg
    - extract:
        key: glauth
    - extract:
        key: grafana