---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: kube-prometheus
spec:
  chart:
    spec:
      chart: prometheus-community/kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 58.4.0
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: kube-prometheus-stack
  targetNamespace: kube-prometheus
  upgrade:
    crds: CreateReplace