---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: home-assistant
      version: 0.2.60
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      enabled: true
      className: "external"
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        external-dns.alpha.kubernetes.io/target: "external.jacob-williams.me"
      hosts:
        - host: hass.jacob-williams.me
          paths:
            - path: /
              pathType: ImplementationSpecific
    persistence:
      enabled: true
      storageClass: "longhorn"
    addons:
      codeserver:
        enabled: true
        ingress:
          enabled: true
          className: "internal"
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTP
          hosts:
          - host: code-server.jacob-williams.me
            paths:
              - path: /
                pathType: ImplementationSpecific