---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minio-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: operator
      version: 5.0.10
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    console:
      ingress:
        enabled: true
        ingresClassName: "internal"
        host: "minio.jacob-williams.me"