---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: default
spec:
  entryPoints:
    - internalsecure
  routes:
    - match: Host(`whoami.internal.jacob-williams.me`)
      kind: Rule
      services:
        - name: whoami
          port: 80
          scheme: http
          passHostHeader: true
      middlewares:
        - name: default-headers