---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: default
  labels:
    trafik.enabled: "true"
    traefik.http.routers.whoami.entroypoints: "http"
    traefik.http.routers.whoami.rule: Host(`whoami.jimsgarage.co.uk`)
    traefik.http.middlewares.whoami-https-redirect.redirectscheme.scheme: https
    traefik.http.routers.whoami.middlewares: whoami-https-redirect
    traefik.http.routers.whoami-secure.entrypoints: https
    traefik.http.routers.whoami-secure.rule: Host(`whoami.jimsgarage.co.uk`)
    traefik.http.routers.whoami-secure.tls: "true"
    traefik.http.routers.whoami-secure.service: whoami
    traefik.http.services.whoami.loadbalancer.server.port: "80"

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: whoami