---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
 name: bgp-peering-policy-worker
spec:
 nodeSelector:
   matchLabels:
     metal.sidero.dev/serverclass: worker
 virtualRouters:
 - localASN: 65552
   serviceSelector:
     matchExpressions:
       - {key: "io.cilium/bgp-announce", operator: In, values: ['worker']}
   neighbors:
    - peerAddress: '10.0.40.1/32'
      peerASN: 65551
      eBGPMultihopTTL: 10
      connectRetryTimeSeconds: 120
      holdTimeSeconds: 90
      keepAliveTimeSeconds: 30
      gracefulRestart:
        enabled: true
        restartTimeSeconds: 120